# SPDX-FileCopyrightText: 2025 Iconica
#
# SPDX-License-Identifier: GPL-3.0-or-later

include: package:flutter_iconica_analysis/components_options.yaml

# Possible to overwrite the rules from the package

analyzer:
  exclude:
  
linter:
  rules:
