name: dart_feed_utilities
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  rxdart: ^0.28.0
  

dev_dependencies:
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0
  test: ^1.24.0
