# SPDX-FileCopyrightText: 2023 Iconica
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: flutter_timeline

packages:
  - packages/**

command:
  version:
    branch: master

scripts:
  lint:all:
    run: dart run melos run analyze && dart run melos run format-check
    description: Run all static analysis checks.

  get:
    run: |
      dart run melos exec -c 1 -- "flutter pub get"
      dart run melos exec --scope="*example*" -c 1 -- "flutter pub get"

  upgrade:
    run: dart run melos exec -c 1 -- "flutter pub upgrade"

  create:
    # run create in the example folder of flutter_timeline_view
    run: dart run melos exec --scope="*example*" -c 1 -- "flutter create ."

  analyze:
    run: |
      dart run melos exec -c 1 -- \
        flutter analyze --fatal-infos
    description: Run `flutter analyze` for all packages.

  format:
    run: dart run melos exec dart format .
    description: Run `flutter format` for all packages.

  format-check:
    run: dart run melos exec dart format . --set-exit-if-changed
    description: Run `flutter format` checks for all packages.
