# SPDX-FileCopyrightText: 2023 Iconica
#
# SPDX-License-Identifier: GPL-3.0-or-later
name: flutter_feed
description: Visual elements and interface combined into one package
version: 0.1.0
homepage: https://github.com/Iconica-Development/flutter_feed
publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: '>=3.22.2'

dependencies:
  flutter:
    sdk: flutter
  flutter_feed_view:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^0.1.0

  flutter_feed_interface:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^5.1.1
  collection: ^1.18.0
dev_dependencies:
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0
