# SPDX-FileCopyrightText: 2023 Iconica
#
# SPDX-License-Identifier: GPL-3.0-or-later
name: flutter_timeline
description: Visual elements and interface combined into one package
version: 5.0.0
publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_timeline_view:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^5.0.0

  flutter_timeline_interface:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^5.0.0
  collection: any

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 6.0.0

flutter:
