# SPDX-FileCopyrightText: 2023 Iconica
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: flutter_timeline_view
description: Visual elements of the Flutter Timeline Component
version: 4.1.0

publish_to: none

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  cached_network_image: ^3.2.2
  dotted_border: ^2.1.0

  flutter_timeline_interface:
    git:
      url: https://github.com/Iconica-Development/flutter_timeline
      path: packages/flutter_timeline_interface
      ref: 4.1.0
  flutter_image_picker:
    git:
      url: https://github.com/Iconica-Development/flutter_image_picker
      ref: 1.0.5
  collection: any
  flutter_svg: ^2.0.10+1

dependency_overrides:
  flutter_timeline_interface:
    path: ../flutter_timeline_interface

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 6.0.0

flutter:
  assets:
    - assets/

