# SPDX-FileCopyrightText: 2023 Iconica
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: flutter_timeline_view
description: Visual elements of the Flutter Timeline Component
version: 5.0.0
publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  cached_network_image: ^3.2.2
  dotted_border: ^2.1.0
  collection: any
  flutter_svg: ^2.0.10+1
  flutter_timeline_interface:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^5.0.0
  flutter_image_picker:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^1.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 6.0.0

flutter:
  assets:
    - assets/
